//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubloaderWpf.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubloaderWpf.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;language_code&quot;:&quot;af&quot;,&quot;language_name&quot;:&quot;Afrikaans&quot;},{&quot;language_code&quot;:&quot;sq&quot;,&quot;language_name&quot;:&quot;Albanian&quot;},{&quot;language_code&quot;:&quot;ar&quot;,&quot;language_name&quot;:&quot;Arabic&quot;},{&quot;language_code&quot;:&quot;an&quot;,&quot;language_name&quot;:&quot;Aragonese&quot;},{&quot;language_code&quot;:&quot;hy&quot;,&quot;language_name&quot;:&quot;Armenian&quot;},{&quot;language_code&quot;:&quot;at&quot;,&quot;language_name&quot;:&quot;Asturian&quot;},{&quot;language_code&quot;:&quot;eu&quot;,&quot;language_name&quot;:&quot;Basque&quot;},{&quot;language_code&quot;:&quot;be&quot;,&quot;language_name&quot;:&quot;Belarusian&quot;},{&quot;language_code&quot;:&quot;bn&quot;,&quot;language_name&quot;:&quot;Bengali&quot;},{&quot;language_code&quot;:&quot;bs&quot;,&quot;language_name&quot;:&quot;Bosnian&quot;},{&quot;language_co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LanguagesList {
            get {
                return ResourceManager.GetString("LanguagesList", resourceCulture);
            }
        }
    }
}
